site_name: 2023 级问题求解（程设部分）
theme:
  name: material
  language: zh
  # icon:
  #   annotation: material/arrow-right-circle
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.tooltips

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - pymdownx.tilde
  - abbr
  - attr_list
  - pymdownx.snippets
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

nav:
  - 主版:
    - index.md
    - 课程安排:
      - 总览: schedule/index.md
      - 第一学期: schedule/ps1.md 
  - 指南:
    - start/index.md
    - 快速上手: start/quickstart.md
    - 写在问求之前: start/beforeps.md
    - 代码风格: start/code-style.md
    - 程序设计基础: start/program.md
    - 学习资源推荐: start/learn-more.md 
  - OJ:
    - oj/index.md
    - 第一学期:
      - 第一学期首页: oj/ps1/index.md
      - 1-0:
        - 讲义: oj/ps1/1-0.md
        - 题解: oj/ps1/1-0-sol.md
      - 1-1:
        - 讲义: oj/ps1/1-1.md
        - 题解: oj/ps1/1-1-sol.md
  - 项目:
    - program/index.md
    - Crazy_Arcade_CLI:
      - 首页: program/ps1/index.md
  - Lab:
    - lab/index.md
  