site_name: 2023 级问题求解（编程部分）
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde

nav:
  - 主页:
    - index.md
  - 上手指南:
    - start/index.md
  - OJ:
    - oj/index.md
  - 项目:
    - program/index.md
    - 梦开始的地方: program/program.md
  - Lab:
    - lab/index.md
  