site_name: 2023 级问题求解（程设部分）

# Repository
repo_name: 'ps-wiki'
repo_url: 'https://github.com/PS2023-programming/ps-wiki'

# Copyright
copyright: 'Copyright &copy; 2023 Problem-Solving (2023) TA Team'

theme:
  name: material
  language: zh
  # icon:
  #   annotation: material/arrow-right-circle
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.tooltips
  icon:
    logo: 'material/school'
  # favicon: 'favicon.ico'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - pymdownx.tilde
  - abbr
  - attr_list
  - pymdownx.snippets
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - 主版:
    - index.md
    - 课程安排:
      - 总览: schedule/index.md
      - 第一学期: schedule/ps1.md 
  - 指南:
    - start/index.md
    - 快速上手: start/quickstart.md
    - 写在问求之前: start/beforeps.md
    - 代码风格: start/code-style.md
    - 程序设计基础:
      - start/program/index.md
      - C++ 基础:
        - Hello, World!: lang/helloworld.md
        - C++ 语法基础: lang/basic.md
        - 变量: lang/var.md
        - 运算: lang/op.md
        - 流程控制语句:
          - 分支: lang/branch.md
          - 循环: lang/loop.md
        - 高级数据类型:
          - 数组: lang/array.md
          - 结构体: lang/struct.md
          - 联合体: lang/union.md
          - 指针: lang/pointer.md
        - 函数: lang/func.md
        - 文件操作: lang/file-op.md
      - C++ 标准库:
        - C++ 标准库简介: lang/csl/index.md
        - STL 容器:
          - STL 容器简介: lang/csl/container.md
          - 迭代器: lang/csl/iterator.md
          - 序列式容器: lang/csl/sequence-container.md
          - 关联式容器: lang/csl/associative-container.md
          - 无序关联式容器: lang/csl/unordered-container.md
          - 容器适配器: lang/csl/container-adapter.md
        - STL 算法: lang/csl/algorithm.md
        - bitset: lang/csl/bitset.md
        - string: lang/csl/string.md
        - pair: lang/csl/pair.md
      - C++ 进阶:
        - 类: lang/class.md
        - 命名空间: lang/namespace.md
        - 值类别: lang/value-category.md
        - 重载运算符: lang/op-overload.md
        - 引用: lang/reference.md
        - 常值: lang/const.md
        - 新版 C++ 特性: lang/new.md
        - Lambda 表达式: lang/lambda.md
        - 编译优化: lang/optimizations.md
      - C++ 与其他常用语言的区别: lang/cpp-other-langs.md
    - 理论环境配置: start/theory.md
    - 资源聚集处: start/learn-more.md 
  - OJ:
    - oj/index.md
    - 第一学期:
      - 第一学期首页: oj/ps1/index.md
      - 1-0:
        - 讲义: oj/ps1/1-0.md
        - 题解: oj/ps1/1-0-sol.md
      - 1-1:
        - 讲义: oj/ps1/1-1.md
        - 题解: oj/ps1/1-1-sol.md
      - 1-2:
        - 题解: oj/ps1/1-2-sol.md
      - 1-3:
        - 题解: oj/ps1/1-3-sol.md
      - 1-4:
        - 题解: oj/ps1/1-4-sol.md
      - 1-5:
        - 题解: oj/ps1/1-5-sol.md
      - 1-6:
        - 题解: oj/ps1/1-6-sol.md
      - 1-7:
        - 题解: oj/ps1/1-7-sol.md
      - 1-8:
        - 题解: oj/ps1/1-8-sol.md
      - 1-9:
        - 题解: oj/ps1/1-9-sol.md
      - 1-10:
        - 题解: oj/ps1/1-10-sol.md
  - 项目:
    - program/index.md
    - NJU Universalis（问求风云）:
      - 首页: program/ps1/index.md
      - 零：环境配置和上手: 
        - program/ps1/0/index.md
        - 梦开始的地方: program/ps1/0/getcode.md
        - 基础设施: program/ps1/0/complete_shell.md
      - 一：Hello, Minitui!:
        - program/ps1/1/index.md
        - RTFSC（框架代码导读）: program/ps1/1/learn_program.md
        - 组件管理与绘制: program/ps1/1/draw.md
        - 用户输入与事件: program/ps1/1/event.md
      - 二：地图编辑器:
        - program/ps1/2/index.md
        - 多组件与布局: program/ps1/2/layout.md
        - 地图显示与编辑: program/ps1/2/map.md
        - 地图数据持久化: program/ps1/2/serialization.md
  - Lab:
    - lab/index.md
  